# Generated by Django 4.1.5 on 2023-06-09 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="code",
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name="article",
            unique_together={("code", "language")},
        ),
    ]
