# Generated by Django 4.1.5 on 2023-06-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_code_alter_article_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="is_menu_visible",
        ),
        migrations.RemoveField(
            model_name="article",
            name="menu_display_name",
        ),
        migrations.RemoveField(
            model_name="article",
            name="sub_menu",
        ),
        migrations.DeleteModel(
            name="SubMenu",
        ),
    ]
