# Generated by Django 4.1.5 on 2024-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_remove_article_is_menu_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="add_to_menu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="menu_order",
            field=models.IntegerField(
                default=0,
                help_text="Articles with lower number will be displayed first in menu.",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[("pl", "Polski"), ("en", "Angielski")], max_length=2
            ),
        ),
    ]
