# Generated by Django 4.1.5 on 2024-12-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_article_add_to_menu_article_menu_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Artykuł", "verbose_name_plural": "Artykuły"},
        ),
        migrations.AlterModelOptions(
            name="articleimage",
            options={
                "verbose_name": "Obrazek artykułu",
                "verbose_name_plural": "Obrazki artykułów",
            },
        ),
    ]
