# Generated by Django 4.1.5 on 2023-01-28 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("place", models.CharField(max_length=100)),
                ("is_draft", models.BooleanField(default=True)),
                ("is_ended", models.BooleanField(default=False)),
                ("results", models.TextField(blank=True, null=True)),
                ("organizer", models.TextField()),
                ("referee", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("address_map_link", models.URLField(blank=True, null=True)),
                ("prizes", models.TextField(blank=True, null=True)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("prepaid_option", models.BooleanField(default=False)),
                ("game_rules", models.TextField(blank=True, null=True)),
                ("komi", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "rules_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mac_mahon", "MacMahon"),
                            ("swiss", "Swiss"),
                            ("round_robin", "Round Robin"),
                            ("swiss_round_robin", "Swiss Round Robin"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tournament_class",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("rounds", models.IntegerField(blank=True, null=True)),
                (
                    "handicap_rules",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "time_control",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("player_limit", models.IntegerField(blank=True, null=True)),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Info",
                "verbose_name_plural": "Registration Info",
            },
        ),
        migrations.CreateModel(
            name="RegisteredPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name and surname"),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("9_dan", "9 dan"),
                            ("8_dan", "8 dan"),
                            ("7_dan", "7 dan"),
                            ("6_dan", "6 dan"),
                            ("5_dan", "5 dan"),
                            ("4_dan", "4 dan"),
                            ("3_dan", "3 dan"),
                            ("2_dan", "2 dan"),
                            ("1_dan", "1 dan"),
                            ("1_kyu", "1 kyu"),
                            ("2_kyu", "2 kyu"),
                            ("3_kyu", "3 kyu"),
                            ("4_kyu", "4 kyu"),
                            ("5_kyu", "5 kyu"),
                            ("6_kyu", "6 kyu"),
                            ("7_kyu", "7 kyu"),
                            ("8_kyu", "8 kyu"),
                            ("9_kyu", "9 kyu"),
                            ("10_kyu", "10 kyu"),
                            ("11_kyu", "11 kyu"),
                            ("12_kyu", "12 kyu"),
                            ("13_kyu", "13 kyu"),
                            ("14_kyu", "14 kyu"),
                            ("15_kyu", "15 kyu"),
                            ("16_kyu", "16 kyu"),
                            ("17_kyu", "17 kyu"),
                            ("18_kyu", "18 kyu"),
                            ("19_kyu", "19 kyu"),
                            ("20_kyu", "20 kyu"),
                            ("21_kyu", "21 kyu"),
                            ("22_kyu", "22 kyu"),
                            ("23_kyu", "23 kyu"),
                            ("24_kyu", "24 kyu"),
                            ("25_kyu", "25 kyu"),
                            ("26_kyu", "26 kyu"),
                            ("27_kyu", "27 kyu"),
                            ("28_kyu", "28 kyu"),
                            ("29_kyu", "29 kyu"),
                            ("30_kyu", "30 kyu"),
                        ],
                        max_length=200,
                    ),
                ),
                ("city_club", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("egf_pid", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_players",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
