# Generated by Django 4.1.5 on 2023-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredplayer",
            name="rank",
            field=models.CharField(
                choices=[
                    ("5p", "5 pro"),
                    ("4p", "4 pro"),
                    ("3p", "3 pro"),
                    ("2p", "2 pro"),
                    ("1p", "1 pro"),
                    ("9d", "9 dan"),
                    ("8d", "8 dan"),
                    ("7d", "7 dan"),
                    ("6d", "6 dan"),
                    ("5d", "5 dan"),
                    ("4d", "4 dan"),
                    ("3d", "3 dan"),
                    ("2d", "2 dan"),
                    ("1d", "1 dan"),
                    ("1k", "1 kyu"),
                    ("2k", "2 kyu"),
                    ("3k", "3 kyu"),
                    ("4k", "4 kyu"),
                    ("5k", "5 kyu"),
                    ("6k", "6 kyu"),
                    ("7k", "7 kyu"),
                    ("8k", "8 kyu"),
                    ("9k", "9 kyu"),
                    ("10k", "10 kyu"),
                    ("11k", "11 kyu"),
                    ("12k", "12 kyu"),
                    ("13k", "13 kyu"),
                    ("14k", "14 kyu"),
                    ("15k", "15 kyu"),
                    ("16k", "16 kyu"),
                    ("17k", "17 kyu"),
                    ("18k", "18 kyu"),
                    ("19k", "19 kyu"),
                    ("20k", "20 kyu"),
                    ("21k", "21 kyu"),
                    ("22k", "22 kyu"),
                    ("23k", "23 kyu"),
                    ("24k", "24 kyu"),
                    ("25k", "25 kyu"),
                    ("26k", "26 kyu"),
                    ("27k", "27 kyu"),
                    ("28k", "28 kyu"),
                    ("29k", "29 kyu"),
                    ("30k", "30 kyu"),
                ],
                max_length=10,
            ),
        ),
    ]
