# Generated by Django 4.1.5 on 2023-05-12 12:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentresult",
            name="order",
            field=models.IntegerField(
                default=0, help_text="higher number = higher shown on the page"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentresult",
            name="result_file",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="tournament_results/",
            ),
        ),
    ]
