# Generated by Django 4.1.5 on 2023-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_tournamentresult_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="is_draft",
            field=models.BooleanField(
                default=True,
                help_text="If true then tournament will not be displayed on the website tournament list but detail page will be accessible by URL.",
            ),
        ),
    ]
