# Generated by Django 4.1.5 on 2023-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_alter_registeredplayer_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="fee",
            field=models.TextField(blank=True, null=True),
        ),
    ]
