# Generated by Django 4.1.5 on 2023-04-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_alter_tournament_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
