# Generated by Django 4.1.5 on 2023-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_registration_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="description_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="additional_info_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="additional_info_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="address_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="address_map_link_en",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="address_map_link_pl",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="address_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="description_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="fee_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="fee_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="game_rules_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="game_rules_pl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="handicap_rules_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="handicap_rules_pl",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="name_pl",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="prizes_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="prizes_pl",
            field=models.TextField(blank=True, null=True),
        ),
    ]
