# Generated by Django 4.1.5 on 2023-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_alter_tournamentresult_result_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="is_ended",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="If tournament lasts one day then leave this field empty.",
                null=True,
            ),
        ),
    ]
