# Generated by Django 4.1.5 on 2023-06-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_remove_tournament_is_ended_alter_tournament_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="email_required",
            field=models.BooleanField(default=False),
        ),
    ]
