# Generated by Django 4.1.5 on 2023-04-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_registration_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("activity_name", models.CharField(max_length=400)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_activities",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Activity",
                "verbose_name_plural": "Scheduled Activities",
            },
        ),
    ]
