# Generated by Django 4.1.5 on 2023-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_scheduledactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledactivity",
            name="activity_name_en",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="scheduledactivity",
            name="activity_name_pl",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
