# Generated by Django 4.1.5 on 2024-12-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_tournamentinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournament",
            options={
                "verbose_name": "Turniej (stare)",
                "verbose_name_plural": "Turnieje (stare)",
            },
        ),
    ]
