# Generated by Django 4.1.5 on 2023-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_remove_tournament_results_tournament_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="place_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="place_pl",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
