# Generated by Django 4.1.5 on 2023-04-24 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0009_tournament_place_en_tournament_place_pl"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="code",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
