# Generated by Django 4.1.5 on 2023-04-26 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="code",
            field=models.CharField(
                default=uuid.UUID("af9cec83-b87c-447f-8f41-4e1532c966e7"),
                max_length=36,
                unique=True,
            ),
        ),
    ]
