# Generated by Django 4.1.5 on 2023-05-17 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_alter_meeting_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="code",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Unique code visible in URL.",
                max_length=36,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="MeetingParticipant",
        ),
    ]
