# Generated by Django 4.1.5 on 2023-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meeting_code_delete_meetingparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
