# Generated by Django 4.1.5 on 2023-10-31 09:05

from django.db import migrations


def populate_meetings_is_active(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    Meeting.objects.update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meeting_is_active"),
    ]

    operations = [
        migrations.RunPython(populate_meetings_is_active),
    ]
