# Generated by Django 4.1.5 on 2023-04-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sgf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tsumego", "Tsumego"),
                            ("review", "Review"),
                            ("club_knowledge", "Club Knowledge"),
                        ],
                        max_length=100,
                    ),
                ),
                ("sgf_file", models.FileField(upload_to="sgfs/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
