# Generated by Django 4.1.5 on 2024-12-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sgfs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sgf",
            options={"verbose_name": "Plik SGF", "verbose_name_plural": "Pliki SGF"},
        ),
    ]
